### ISSUE TITLE
Fresh Database build fails with "Conflicting migrations"

### ISSUE THREAD

**Issue by OrangeCrush** [phalt/pokeapi#114]
Hello again guys-

I noticed the following error when trying to build the database from scratch

```bash
root@pokeapi-dev:~/pokeapi# python manage.py migrate --settings=config.docker
CommandError: Conflicting migrations detected (0001_squashed_0006_pokemonformsprites, 0001_squashed_0002_auto_20151228_0417 in pokemon_v2).
To fix them run 'python manage.py makemigrations --merge'

root@pokeapi-dev:~/pokeapi# python manage.py makemigrations --merge
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/makemigrations.py", line 85, in handle
    return self.handle_merge(loader, conflicts)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/makemigrations.py", line 186, in handle_merge
    raise ValueError("Could not find common ancestor of %s" % migration_names)
ValueError: Could not find common ancestor of set([u'0001_squashed_0006_pokemonformsprites', u'0001_squashed_0002_auto_20151228_0417'])

```
I walked commits backwards and the last commit that I do not see this issue is @c966153
I'm not sure where to start troubleshooting with this one.. Let me know if you think it's a pretty simple fix I could PR myself.

As always, I just wanted to pass on my thanks for everyone's work on this...
I'm super close to being able to ship something I've been working on for awhile and I wouldn't really be anywhere without this project!

**Comment by phalt** [comment]
@zaneadix have you encountered this before?

**Comment by zaneadix** [comment]
@phalt @OrangeCrush oh wow. Big oversight on my part. Looks like the path had diverged so far from the New Data PR and the latest state it was merged into that the base migration was completely different. I'll see if I can knock out a fix for this today.
